# -*- mode: python ; coding: utf-8 -*-
import libusb_package
libusb_dll = libusb_package.get_library_path()

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[(libusb_dll, '.')],
    datas=[('library', 'library')],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'matplotlib',
        'matplotlib.backends.backend_qtagg',
        'serial',
        'serial.tools.list_ports',
        'logging',
        'logging.handlers',
        'core.bootloader',
        'core.can_id_loader',
        'core.can_protocol',
        'core.dfu',
        'core.dbc_manager',
        'core.dbc_parser',
        'core.fake_serial',
        'core.script_engine',
        'core.serial_manager',
        'core.update_checker',
        'models.config',
        'models.logger',
        'models.translations',
        'models.utils',
        'ui.can_analyzer',
        'ui.can_gateway_tab',
        'ui.can_graph_tab',
        'ui.can_monitor_tab',
        'ui.can_trigger_tab',
        'ui.com_settings_dialog',
        'ui.dark_theme',
        'ui.firmware_page',
        'ui.flexible_logic_tab',
        'ui.hex_edit',
        'ui.id_edit',
        'ui.library_browser',
        'ui.logic_tab',
        'ui.script_editor',
        'ui.settings_window',
        'ui.signal_graph_tab',
        'ui.ui_utils',
        'pyqtgraph',
        'cantools',
        'cantools.database',
        'carbus_async',
        'pyocd.core.helpers',
        'pyocd.flash.flash_builder',
        'pyocd.probe.stlink_probe',
        'pyocd.probe.jlink_probe',
        'pyocd.target',
        'pyocd.target.family',
        'pylink',
        'pylink.enums',
        'usb',
        'usb.backend.libusb1',
        'libusb_package',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CodeMaster',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='assets/icon.ico',
)
